---

title: Гром и молния
timezone: UTC
description: Произведения цифрового искусства для частных интерьеров или публичных пространств
room-projector: 167480
hall-projector: 0
street-projector: 0
room-player: 11250
hall-player: 11250
street-player: 11250
room-screen: 0
hall-screen: 35000
street-screen: 70000


show_sidebar: false
show_downloads: false
show_title: false
show_description: false
git_branch: master

theme: jekyll-theme-minimal

include: ['.htaccess']

exclude:
  template.md
  template.html

use_github_wiki: false
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

prose:
  rooturl: 'https://multimedia-loom.ml '
  siteurl: 'https://multimedia-loom.ml '
  relativeLinks: 'https://prose.github.io/starter/links.jsonp'
  media: '/images'

  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /assets
    - 404.md
    - README.md
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
